export const featuresPro = [
    {
        title: 'Formula',
        thumbnail: '/formula.svg',
        description: 'Complex formulas similar to Excel. Provides dynamic calculations & data manipulation.',  
    },
    {
        title: 'Master Detail',
        thumbnail: '/master-detail.svg',
        description: 'Expand rows to  reveal detailed child information. Display additional data or build customizable subtables within the grid.',     
    },
    {
        title: 'Merge Cells',
        thumbnail: '/merge.svg',
        description: 'Combine adjacent cells into a single cell.',
        sponsor: '/guide/cell/merge',
    },
    {
        thumbnail: '/row-transpose.svg',
        title: 'Row Transpose',
        description: 'Modify the grid by transposing its data: columns become rows and vice versa.',
    },
    {
        title: 'Excel Export',
        thumbnail: '/export.svg',
        description: 'Export data to Excel format. Supported types include `xlsx`, `xlsm`, `xlsb`, `xls`, and more.',
        sponsor: '/guide/export.excel',
    },
    {
        title: 'Pagination',
        thumbnail: '/pagination.svg',
        description: 'Break larger datasets into smaller pages, enhancing both performance and user experience.',
        sponsor: '/guide/pagination',
    },
    {
        title: 'Event Manager',
        thumbnail: '/event-manager.svg',
        description: 'Handles, customizes, and optimizes events. Creates complex interactions and workflows.',
        sponsor: '/guide/event-manager',
    },
    {
        title: 'Advanced Filtering',
        thumbnail: '/filtering.svg',
        description: 'Advanced multi-condition filters and custom filter logic to refine and display your data more effectively.',
        sponsor: '/guide/advanced-filtering',
    },
    {
        title: 'Conditional Formatting',
        thumbnail: '/conditional-formatting.svg',
        description: 'Customize cell styles based on specific conditions. Highlight important data, create visual cues, and improve the readability.',
        sponsor: '/guide/conditional-formatting',
    },
    {
        title: 'Cell Flash',
        thumbnail: '/cell-flash.svg',
        description: 'Enable flashing cells to highlight updates, making it easy for users to spot changes in values.',
        sponsor: '/guide/cell/flash',
    },
    {
        title: 'Cell Animating Changes',
        thumbnail: '/cell-animate.svg',
        description: 'Animate changes in cell values with directional arrows to indicate increases or decreases.',
        sponsor: '/guide/cell/animating-changes',
    },
    {
        title: 'Data Validation',
        thumbnail: '/data-validation.svg',
        description: 'Built-in data validation to ensure data integrity. Define customizable validation rules and error handling to maintain high-quality data.',
        sponsor: '/guide/data-validation',
    },
    {
        title: 'Column Stretch',
        thumbnail: '/column-stretch.svg',
        description: 'Automatically adjusts column widths to fit the grid layout efficiently.',
        sponsor: '/guide/column/stretch',
    },
    {
        title: 'Column Selection',
        thumbnail: '/column-selection.svg',
        description: 'Enable easy selection of entire columns for enhanced data manipulation.',
        sponsor: '/guide/column/selection',
    },
    {
        title: 'Clipboard with JSON and Advanced Objects',
        thumbnail: '/clipboard.svg',
        description: 'Support for JSON and other objects. Copy and paste complex data structures explained.',
        sponsor: '/guide/clipboard.pro',
    },
    {
        title: 'Advanced Drag and Drop',
        thumbnail: '/drag-and-drop.svg',
        description: "Sophisticated drag-and-drop functionality with custom behavior and interactions, enhancing the grid's interactivity and usability.",
        sponsor: '/guide/drag-and-drop',
    },
    {
        title: 'Plugin Explained',
        thumbnail: '/plugin.svg',
        description: 'Documentation and examples explaining how to create and use plugins to extend the functionality of the grid.',
        sponsor: '/guide/plugin',
    },
    {
        title: 'Data Processing',
        thumbnail: '/data-sync.svg',
        description: 'Example of how to process data from/to external sources.',
        sponsor: '/guide/data-sync',
    },
    {
        title: 'Reference Data',
        thumbnail: '/reference-data.svg',
        description: 'Manage static key/value pairs for displaying meaningful labels alongside coded values.',
        sponsor: '/guide/reference-data',
    },
    {
        title: 'Auto-Focus on Next Line',
        thumbnail: '/auto-focus.svg',
        description: 'Automatically move focus to the next row for streamlined data entry and editing.',
        sponsor: '/guide/auto-focus',
    },
    {
        title: 'Row Odd Styling',
        thumbnail: '/odd-rows.svg',
        description: 'Apply distinct styles to odd rows for improved readability and data distinction.',
        sponsor: '/guide/odd-rows',
    },
    {
        title: 'Row Checkbox Selection',
        thumbnail: '/row-selection.svg',
        description: 'Select rows using checkboxes and perform actions on selected data.',
        sponsor: '/guide/row/selection',
    },
    {
        title: 'Row Custom Heading',
        thumbnail: '/row-heading.svg',
        description: 'Add custom heading to rows for improved readability and data distinction.',
        sponsor: '/guide/row/heading',
    },
    {
        title: 'Overlay layers',
        thumbnail: '/overlay.svg',
        description: 'Push and pop layers on top of the grid to enhance the user experience.',
    },
    // {
    //   title: 'Audit Trail/History',
    //   thumbnail: '/audit-trail.svg',
    //   description: 'Track changes made to the grid data with a detailed history of edits. Maintain an audit trail for data modifications, enabling review and accountability.',
    //   sponsor: '/guide/audit-trail',
    //   actionText,
    // },
    // {
    //   title: 'Advanced Multiple Selection with Ctrl (CMD) Key',
    //   thumbnail: '/multiple-selection.svg',
    //   description: 'Implement advanced multiple selection capabilities using the Ctrl (CMD) key. This allows users to select multiple, non-adjacent cells or rows, enhancing data manipulation and interaction within the grid.',
    //   sponsor: '/guide/multiple-selection',
    //   actionText,
    // },

    // {
    //   title: 'SSR render',
    //   thumbnail: '/ssr-render.svg',
    //   description: 'Pro examples on how to render Revogrid in SSR applications across frameworks.',
    //   sponsor: '/guide/ssr-render',
    //   actionText,
    // },
    // {
    //   title: 'Inline Editing Enhancements',
    //   thumbnail: '/inline-editing.svg',
    //   description: 'Enhance inline editing capabilities with custom editors, validation rules, and real-time data updates.',
    //   sponsor: '/guide/inline-editing',
    //   actionText,
    // },
    // {
    //   title: 'Custom Themes and Styling',
    //   thumbnail: '/custom-themes.svg',
    //   description: 'Create and apply custom themes to your grid, allowing extensive styling and branding options. Customize the appearance of your grid to match your application\'s design.',
    //   sponsor: '/guide/custom-themes',
    //   actionText,
    // },
    // {
    //   title: 'Hierarchical Data Support',
    //   thumbnail: '/hierarchical-data.svg',
    //   description: 'Support nested rows and tree structures to represent hierarchical data within your grid. Easily manage and display parent-child relationships and complex data structures.',
    //   sponsor: '/guide/hierarchical-data',
    //   actionText,
    // },
]
