import { title } from "process";

export const featuresPro = [
    {
        title: 'Pagination',
        thumbnail: '/pagination.svg',
        description: 'Break larger datasets into smaller pages, enhancing both performance and user experience.',
        videoUrl: '/video/pagination.mp4',
    },
    {
        title: 'Formula',
        thumbnail: '/formula.svg',
        videoUrl: '/video/formula.mp4',
        description: 'Complex formulas similar to Excel. Provides dynamic calculations & data manipulation.',  
    },
    {
        title: 'Trail History',
        thumbnail: '/history.svg',
        videoUrl: '/video/history.mp4',
        description: 'Track your history of changes. Undo and redo operations.',  
    },
    {
        title: 'Conditional Formatting',
        thumbnail: '/conditional-formatting.svg',
        description: 'Customize cell styles based on specific conditions. Highlight important data, create visual cues, and improve the readability.',
        videoUrl: '/video/conditional-formatting.mp4',
    },
    {
        title: 'Cell Flash',
        thumbnail: '/cell-flash.svg',
        description: 'Enable flashing cells to highlight updates, making it easy for users to spot changes in values.',
        videoUrl: '/video/cell-flash.mp4',
    },
    {
        title: 'Merge Cells',
        thumbnail: '/merge.svg',
        description: 'Combine adjacent cells into a single cell.',
        videoUrl: '/video/merge.mp4',
    },
    {
        title: 'Data Validation',
        thumbnail: '/data-validation.svg',
        description: 'Built-in data validation to ensure data integrity. Define customizable validation rules and error handling to maintain high-quality data.',
        videoUrl: '/video/data-validation.mp4',
    },
    {
        title: 'Reference Data',
        thumbnail: '/reference-data.svg',
        description: 'Manage static key/value pairs for displaying meaningful labels alongside coded values.',
        videoUrl: '/video/reference-data.mp4',
    },
    {
        title: 'Tree Data View',
        thumbnail: '/tree-data.svg',
        description: 'Display hierarchical data in a tree-like structure, enabling navigation and organization.',
        videoUrl: '/video/tree-data.mp4',
    },
    {
        title: 'Master Detail',
        thumbnail: '/master-detail.svg',
        videoUrl: '/video/master-detail.mp4',
        description: 'Expand rows to  reveal detailed child information. Display additional data or build customizable subtables within the grid.',     
    },
    {
        thumbnail: '/row-transpose.svg',
        title: 'Row Transpose',
        description: 'Modify the grid by transposing its data: columns become rows and vice versa.',
        videoUrl: '/video/row-transpose.mp4',
    },
    {
        title: 'Row Odd Styling',
        thumbnail: '/odd-rows.svg',
        description: 'Apply distinct styles to odd rows for improved readability and data distinction.',
        videoUrl: '/video/row-odd.mp4',
    },
    {
        title: 'Row Custom Heading',
        thumbnail: '/row-heading.svg',
        description: 'Add custom heading to rows for improved readability and data distinction.',
        videoUrl: '/video/row-heading.mp4',
    },
    {
        title: 'Row Advanced Drag and Drop',
        thumbnail: '/drag-and-drop.svg',
        description: "Sophisticated drag-and-drop functionality with custom behavior and interactions, enhancing the grid's interactivity and usability.",
        videoUrl: '/video/drag-and-drop.mp4',
    },
    {
        title: 'Row Checkbox Selection',
        thumbnail: '/row-selection.svg',
        description: 'Select rows using checkboxes and perform actions on selected data.',
        videoUrl: '/video/row-selection.mp4',
    },
    {
        title: 'Column Stretch',
        thumbnail: '/column-stretch.svg',
        description: 'Automatically adjusts column widths to fit the grid layout efficiently.',
        videoUrl: '/video/column-stretch.mp4',
    },
    {
        title: 'Column Selection',
        thumbnail: '/column-selection.svg',
        description: 'Enable easy selection of entire columns for enhanced data manipulation.',
        videoUrl: '/video/column-selection.mp4',
    },
    {
        title: 'Next Line Focus (WCAG)',
        thumbnail: '/auto-focus.svg',
        description: 'Automatically move focus to the next row for streamlined data entry and editing.',
        videoUrl: '/video/auto-focus.mp4',
    },
    {
        title: 'Clipboard with JSON and Advanced Objects',
        thumbnail: '/clipboard.svg',
        description: 'Support for JSON and other objects. Copy and paste complex data structures explained.',
        videoUrl: '/video/clipboard.mp4',
    },
    {
        title: 'Context Menu',
        thumbnail: '/menu.svg',
        description: 'Customize context menu options. Add custom actions to the grid.',
        videoUrl: '/video/row-heading.mp4',
    },
    {
        title: 'Excel Export',
        thumbnail: '/export.svg',
        description: 'Export data to Excel format. Supported types include `xlsx`, `xlsm`, `xlsb`, `xls`, and more.',
        videoUrl: '/video/excel-export.mp4',
    },
    {
        title: 'Event Manager',
        thumbnail: '/event-manager.svg',
        description: 'Handles, customizes, and optimizes events. Creates complex interactions and workflows.',
        sponsor: '/guide/event-manager',
    },
    {
        title: 'Multi-Filtering',
        thumbnail: '/filtering.svg',
        description: 'Multi-condition filters logic example to refine and display your data more effectively.',
        videoUrl: '/video/filter-multi.mp4',
    },
    {
        title: 'Advanced Selection Filtering',
        thumbnail: '/filtering.svg',
        description: 'Advanced multi-condition filters based on selection.',
        videoUrl: '/video/filter-advance.mp4',
    },
    {
        title: 'Advanced Slider Filtering',
        thumbnail: '/filtering.svg',
        description: 'Advanced slider filter, defining a range of values for filtering.',
        videoUrl: '/video/filter-advance-slider.mp4',
    },
    {
        title: 'Header Input Filtering',
        thumbnail: '/filtering.svg',
        description: 'Header input filter, filtering data based on user input in the first row.',
        videoUrl: '/video/filter-header.mp4',
    },
    {
        title: 'Data Processing',
        thumbnail: '/data-sync.svg',
        description: 'Example of how to process data from/to external sources.',
        sponsor: '/guide/data-sync',
    },
    {
        title: 'Overlay layers',
        thumbnail: '/overlay.svg',
        description: 'Push and pop layers on top of the grid to enhance the user experience.',
    },
]
